# Configuration file for dev environment. Will apply to all functions, but will be overwritten by
# configurations files in specific function folder.
data_set_id: 4040581189836313
tenant_id: 16e3985b-ebe8-4e24-9da4-933e21a9fc81
cdf_cluster: westeurope-1
cdf_project: cdf-bootcamp-04-prod
#just making a commented chnage to run it in prod env as github will not do it if no changes have been made
